language: c
compiler: gcc

# Tool setup.
install:
  - sudo apt-get install -qq luarocks
  - sudo luarocks install lpeg
  - sudo luarocks install linenoise

# Build and test.
script:
  - cd src
  - pwd
  - make
  - ./tvmjit -v
  - make fulltest
